title: Adil Sahab # your name (or website title) here
logo: /assets/img/adil_photo.jpeg # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Engineer with an MSc in Data Analytics and Machine Learning, with 14+ years of expertise in Data Warehousing, Modeling, ETL, and Business Intelligence. Proven track record of delivering high-impact solutions for top-tier companies like Apple and Cisco, which includes a 7-year tenure in the USA.
  <br>
  <a href="https://www.linkedin.com/in/adil-sahab-94a24936/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
