title: Adil Sahab # your name (or website title) here
logo: /assets/img/adil_headshot_circle.png # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) # 
  Data Engineer with an MSc in Data Analytics and Machine Learning, experienced in data warehousing, modeling, ETL, and BI, with a track record at companies like Apple and Cisco. Currently applying these skills to environmental data, with focus on food waste.
  <br><br>
  <a href="https://www.linkedin.com/in/adil-sahab-94a24936/">View my LinkedIn Profile</a>
  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
