title: Adil Sahab # your name (or website title) here
logo: /assets/img/adil_photo.jpeg # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with 4+ years of commercial experience in analytics.
  <br><br>
  <a href="https://www.linkedin.com/in/adil-sahab-94a24936/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
